language: ruby
services: sqlite3
cache: bundler
sudo: false
rvm:
  - 2.2.6
install:
  - cd spec/dummy
  - bundle install --deployment
  - bundle exec rake db:create db:migrate --trace
  - cd ../../
  - bundle install
script:
  - RAILS_ENV=test bin/rspec
